# Generated by Django 3.2.19 on 2023-07-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_ordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
